// Centralized brand / contact constants.
export const BRAND = {
  name: "Rudra Tours & Travels",
  legalName: "Rudra Tours and Travels",
  tagline: "Luxury Journeys Begin Here.",
  founder: "Mr. Abhay Nigam",
  establishedYear: "2014",
  phone: "+91 70145 47628",
  phoneHref: "tel:+917014547628",
  altPhone: "+91 93361 17414",
  altPhoneHref: "tel:+919336117414",
  whatsapp: "+91 70145 47628",
  whatsappHref:
    "https://wa.me/917014547628?text=Hello%20Rudra%20Tours%2C%20I%20would%20like%20to%20book%20a%20cab%20or%20tour%20package.",
  email: "aabhaynigama@gmail.com",
  emailHref: "mailto:aabhaynigama@gmail.com",
  address: "3/46 LIG Swarn Jayanti Vihar, Koyala Nagar, Kanpur, Uttar Pradesh 208001",
  streetAddress: "3/46 LIG Swarn Jayanti Vihar, Koyala Nagar",
  city: "Kanpur",
  state: "Uttar Pradesh",
  postalCode: "208001",
  country: "IN",
  mapsUrl: "https://maps.app.goo.gl/NHcB28bSgL3jEoZW8",
  shortAddress: "Kanpur, Uttar Pradesh",
  hours: "24x7 Cab Booking & Customer Support",
  socialLinks: [] as Array<{ label: string; href: string }>,
  topLocalities: [
    "Civil Lines",
    "Kalyanpur",
    "Kakadeo",
    "Swaroop Nagar",
    "Kidwai Nagar",
    "Govind Nagar",
    "Barra",
    "Naubasta",
    "Panki",
    "Rawatpur",
    "Shyam Nagar",
    "Saket Nagar",
    "Yashoda Nagar",
    "Chakeri",
    "Kanpur Cantt",
    "Arya Nagar",
    "Harsh Nagar",
    "Fazalganj",
  ],
};

