/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursCustomizeRouteImport } from './routes/tours.customize'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursCustomizeRoute = ToursCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => ToursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/gallery': typeof GalleryRoute
  '/inquiry': typeof InquiryRoute
  '/reviews': typeof ReviewsRoute
  '/tours': typeof ToursRouteWithChildren
  '/vehicles': typeof VehiclesRoute
  '/weddings': typeof WeddingsRoute
  '/tours/customize': typeof ToursCustomizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/gallery': typeof GalleryRoute
  '/inquiry': typeof InquiryRoute
  '/reviews': typeof ReviewsRoute
  '/tours': typeof ToursRouteWithChildren
  '/vehicles': typeof VehiclesRoute
  '/weddings': typeof WeddingsRoute
  '/tours/customize': typeof ToursCustomizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/gallery': typeof GalleryRoute
  '/inquiry': typeof InquiryRoute
  '/reviews': typeof ReviewsRoute
  '/tours': typeof ToursRouteWithChildren
  '/vehicles': typeof VehiclesRoute
  '/weddings': typeof WeddingsRoute
  '/tours/customize': typeof ToursCustomizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/gallery'
    | '/inquiry'
    | '/reviews'
    | '/tours'
    | '/vehicles'
    | '/weddings'
    | '/tours/customize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/gallery'
    | '/inquiry'
    | '/reviews'
    | '/tours'
    | '/vehicles'
    | '/weddings'
    | '/tours/customize'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/gallery'
    | '/inquiry'
    | '/reviews'
    | '/tours'
    | '/vehicles'
    | '/weddings'
    | '/tours/customize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  GalleryRoute: typeof GalleryRoute
  InquiryRoute: typeof InquiryRoute
  ReviewsRoute: typeof ReviewsRoute
  ToursRoute: typeof ToursRouteWithChildren
  VehiclesRoute: typeof VehiclesRoute
  WeddingsRoute: typeof WeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/customize': {
      id: '/tours/customize'
      path: '/customize'
      fullPath: '/tours/customize'
      preLoaderRoute: typeof ToursCustomizeRouteImport
      parentRoute: typeof ToursRoute
    }
  }
}

interface ToursRouteChildren {
  ToursCustomizeRoute: typeof ToursCustomizeRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursCustomizeRoute: ToursCustomizeRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  GalleryRoute: GalleryRoute,
  InquiryRoute: InquiryRoute,
  ReviewsRoute: ReviewsRoute,
  ToursRoute: ToursRouteWithChildren,
  VehiclesRoute: VehiclesRoute,
  WeddingsRoute: WeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
